import logging

from flask import Blueprint, flash, jsonify, redirect, render_template, request, session, url_for

from . import auth
from .config import settings
from .recommender import Recommendation
from .services import get_recommender, get_store, save_playlist
from .spotify_client import SpotifyError

log = logging.getLogger(__name__)
bp = Blueprint("adify", __name__)

MAX_PROMPT_LEN = 200


def _flag(data, key: str, default: bool) -> bool:
    if key not in data:
        return default
    return str(data.get(key)).lower() in ("on", "true", "1")


def _read_options(data, is_form: bool) -> dict:
    # HTML forms simply don't send unchecked checkboxes, so for forms a missing
    # key means "off". For JSON a missing key means "use the default".
    default = not is_form
    prompt = (data.get("prompt") or "").strip()[:MAX_PROMPT_LEN]
    try:
        size = int(data.get("size") or settings.playlist_size)
    except (TypeError, ValueError):
        size = settings.playlist_size
    return {
        "prompt": prompt,
        "size": max(5, min(size, 50)),
        "allow_explicit": _flag(data, "explicit", default),
        "two_playlists": _flag(data, "two_playlists", default),
        "save": _flag(data, "save", False),
        "public": _flag(data, "public", default),
    }


def _save(rec: Recommendation, two_playlists: bool, public: bool) -> list[dict]:
    client = auth.user_client()
    title = rec.prompt if len(rec.prompt) <= 60 else rec.prompt[:57] + "..."
    description = f'Generated by ADIFY AI from: "{rec.prompt}"'

    saved = [save_playlist(client, f"ADIFY · {title}", description, rec.main, public)]
    if two_playlists and rec.alternative:
        saved.append(
            save_playlist(client, f"ADIFY · {title} (wider mix)", description, rec.alternative, public)
        )
    return saved


@bp.get("/")
